Repository ansible/galaxy, pull requests merged in 2019-06, with the labels that each got.

#1892 Make combined API perform case insensitive lookups.
  galaxy/api/internal/views/combined.py
Labels: backport

#1893 Fix inefficient queries in legacy search API
  galaxy/api/views/search.py
Labels: backport

#1888 Check collection name conflict with multi-content repo name
  galaxy/api/v2/views/collection.py
Labels: area/backend, priority/medium

#1897 Check collection name conflict with multi-content repo name #1888
  galaxy/api/v2/views/collection.py
Labels: backport

#1900 Admin interface for collections and namespaces
  galaxy/main/admin.py
  galaxy/main/migrations/0143_collection_on_delete.py
  galaxy/main/models/collection.py
  galaxy/main/models/repository.py
Labels: area/frontend, type/enhancement

#1899 Set columns to large on content detail cards. (#1895)
  galaxyui/src/app/content-detail/repository-detail/repository-detail.component.html
Labels: backport

#1901 Improve handling of long namespace descriptions (#1889)
  galaxyui/src/app/authors/detail/author-detail.component.html
  galaxyui/src/app/authors/detail/author-detail.component.less
  galaxyui/src/app/authors/detail/author-detail.component.ts
  galaxyui/src/app/my-content/namespace-list/namespace-list.component.html
  galaxyui/src/app/my-content/namespace-list/namespace-list.component.less
Labels: backport

#1903 Fix typo (#1881)
  galaxyui/src/app/react/components/my-content/content-list.tsx
Labels: backport

#1921 Prevent duplicate ns on login when github username case changes #1919
  galaxy/main/signals/handlers.py
  galaxy/main/tests/test_login_handler.py
Labels: backport

#1922 Check file size on collection import
  galaxy/api/v2/views/collection.py
  galaxy/constants.py
Labels: area/backend

#1923 Check file size on collection import (#1922)
  galaxy/api/v2/views/collection.py
  galaxy/constants.py
Labels: backport

#1916 proposal to add link back to Galaxy from docs (#1909)
  docs/docsite/_themes/sphinx_rtd_theme/layout.html
Labels: backport

#1939 Add collections list action to api
  galaxy/api/v2/tests/test_collection_views.py
  galaxy/api/v2/views/collection.py
Labels: backport
