Repository ansible/galaxy, pull requests merged in 2019-02, with the labels that each got.

#1519 Set community score to average of questions in survey
  docs/docsite/rst/contributing/content_scoring.rst
  galaxy/api/views/survey.py
  galaxy/main/migrations/0125_community_score_question_average.py
  galaxyui/src/app/content-detail/cards/survey/community-survey.component.html
  galaxyui/src/app/content-detail/repository/repository.component.html
  galaxyui/src/app/content-detail/shared/score-bar/score-bar.component.html
  galaxyui/src/app/content-detail/shared/score-bar/score-bar.component.less
  galaxyui/src/app/content-detail/shared/score-bar/score-bar.component.ts
Labels: backport

#1523 Fix 'value too long for type character varying(256)'
  galaxy/main/migrations/0126_notification_commit_message.py
  galaxy/main/models.py
Labels: backport

#1531 Fixed pagination on namespaces with multiple provider namespaces (#1530)
  galaxyui/src/app/my-content/namespace-list/content/repositories-content/repositories-content.component.ts
Labels: backport

#1541 Fix pagination for roles list API
  galaxy/api/views/roles.py
Labels: backport

#1552 Fix updating role dependencies when empty #1545
  galaxy/worker/importers/role.py
Labels: backport

#1553 Support for ansible-lint 4.1.0 #1551
  galaxy/worker/tasks.py
Labels: backport

#1558 Let angular services handle URI encoding. (#1547)
  galaxyui/src/app/search/search.component.ts
Labels: backport

#1560 Send user back to first page when they make searches. (#1550)
  galaxyui/src/app/search/search.component.html
  galaxyui/src/app/search/search.component.ts
Labels: backport

#1561 Add documentation and issue template for requesting a new namespace. …
  .github/ISSUE_TEMPLATE/New_namespace.md
  docs/docsite/rst/contributing/importing.rst
Labels: backport

#1572 Add flake8 GitHub Action to the repo workflow
  .github/main.workflow
Labels: area/infrastructure, type/enhancement

#1583 Move importing validation from celery worker into importer
  galaxy/importer/loaders/apb.py
  galaxy/importer/loaders/role.py
  galaxy/importer/repository.py
  galaxy/importer/tests/test_role_loader.py
  galaxy/worker/importers/apb.py
  galaxy/worker/importers/base.py
  galaxy/worker/importers/role.py
Labels: area/backend, type/enhancement

#1578 Move quality scoring from worker to importer
  galaxy/importer/loaders/base.py
  galaxy/importer/loaders/role.py
  galaxy/importer/models.py
  galaxy/importer/repository.py
  galaxy/worker/tasks.py
Labels: area/backend, type/enhancement

#1579 Initial collection support in importer
  galaxy/importer/collection.py
  galaxy/importer/exceptions.py
  galaxy/importer/models.py
  galaxy/importer/utils/readme.py
  galaxy/pulp/tasks.py
Labels: area/backend, type/enhancement

#1592 Raise forbidden error if un authenticated users load email api. (#1548)
  galaxy/api/views/email.py
Labels: backport
