Repository ansible/galaxy, pull requests merged in 2019-04, with the labels that each got.

#1707 Store serialized collection content on import
  galaxy/importer/collection.py
  galaxy/pulp/tasks.py
Labels: area/backend

#1716 Update content serialization to display platform release
  galaxy/api/internal/serializers/collections.py
  galaxy/importer/collection.py
Labels: area/backend, type/bug

#1719 Document how to list out installed roles
  docs/docsite/rst/using/installing.rst
Labels: area/documentation

#1718 Render collection-level readme on import
  galaxy/importer/collection.py
  galaxy/importer/tests/test_readme_utils.py
  galaxy/importer/utils/readme.py
  galaxy/main/migrations/0139_collection_version_readme.py
  galaxy/main/models/collection.py
  galaxy/worker/tasks/collection.py
  requirements/dev-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: area/backend

#1746 Implement artifact download API endpoint
  galaxy/api/v2/tests/test_collection_version_views.py
  galaxy/api/v2/urls.py
  galaxy/api/v2/views/__init__.py
  galaxy/api/v2/views/collection.py
  galaxy/api/v2/views/collection_version.py
  galaxy/main/models/collection.py
  galaxy/settings/default.py
Labels: area/backend, type/enhancement

#1761 Use absolute urls in api/v2 endpoints
  galaxy/api/fields.py
  galaxy/api/v2/serializers/collection.py
  galaxy/api/v2/tests/test_collection_import_views.py
  galaxy/api/v2/tests/test_collection_version_views.py
  galaxy/api/v2/tests/test_collection_views.py
  galaxy/api/v2/tests/test_task_serializers.py
  galaxy/api/v2/views/collection.py
  galaxy/api/v2/views/collection_version.py
  galaxy/templates/rest_framework/api.html
Labels: area/backend
