Repository ansible/galaxy, pull requests merged in 2019-03, with the labels that each got.

#1602 Remove github api status checks
  galaxy/api/views/views.py
Labels: area/backend

#1604 Set galaxy api and celery workers number explicitly
  scripts/docker/release/entrypoint.sh
Labels: area/infrastructure, backport

#1603 Remove github api status checks
  galaxy/api/views/views.py
Labels: area/backend, backport

#1605 Fix content not found issue on content detail page. (#1600)
  galaxyui/src/app/content-detail/content-detail.component.html
Labels: backport

#1615 Collection import changes for updated datamodel
  galaxy/importer/models.py
  galaxy/main/migrations/0129_collection_quality_score_updates.py
  galaxy/main/models/collection.py
  galaxy/pulp/tasks.py
Labels: area/backend

#1632 Set default namespace email to blank. (#1628)
  galaxy/main/signals/handlers.py
Labels: backport

#1640 Filter GH repos api request by user namespace. (#1631)
  galaxy/api/githubapi.py
Labels: backport

#1642 Backport of auth token fix from #1505 to stable/3.1
  galaxy/settings/default.py
Labels: backport

#1634 Collection import uses import task and import task messages
  galaxy/api/serializers/serializers.py
  galaxy/api/v2/views/collection.py
  galaxy/importer/collection.py
  galaxy/main/migrations/0131_import_task_collection_support.py
  galaxy/main/models/importing.py
  galaxy/main/signals/handlers.py
  galaxy/pulp/exceptions.py
  galaxy/pulp/tasks.py
Labels: area/backend

#1647 Fix missing exception type
  galaxy/pulp/tasks.py
Labels: area/backend, type/bug

#1668 Move collection processing outside atomic transaction
  galaxy/pulp/tasks.py
Labels: area/backend

#1666 Allow import of collection with zero contents
  galaxy/importer/collection.py
Labels: area/backend

#1667 Validate dependencies on collection import
  galaxy/importer/models.py
  galaxy/importer/tests/test_collection_info.py
Labels: area/backend

#1674 Save collection metadata as json not json str
  galaxy/importer/models.py
Labels: area/backend, type/bug

#1677 Validate collection version conflict on upload
  galaxy/api/v2/views/collection.py
Labels: area/backend, type/enhancement

#1678 Drop six library
  galaxy/api/filters.py
  galaxy/api/views/base_views.py
  galaxy/api/views/notification.py
  galaxy/api/views/repository.py
  galaxy/api/views/search.py
  galaxy/importer/finders.py
  galaxy/importer/linters/__init__.py
  galaxy/importer/loaders/apb.py
  galaxy/importer/loaders/base.py
  galaxy/importer/loaders/role.py
  galaxy/main/celerytasks/tasks.py
  galaxy/main/mixins.py
  galaxy/worker/utils.py
  requirements/dev-requirements.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: area/backend, type/enhancement

#1673 Collection filename validation against manifest
  galaxy/api/v2/views/collection.py
  galaxy/importer/collection.py
  galaxy/pulp/tasks.py
Labels: area/backend, type/enhancement

#1690 Ignore role tags when not strings
  galaxy/importer/loaders/role.py
Labels: area/backend

#1692 Support license as list and license_file in collection manifest
  galaxy/importer/models.py
  galaxy/importer/tests/test_collection_info.py
Labels: area/backend

#1682 Only allow github repo import if single role
  galaxy/importer/repository.py
Labels: area/backend

#1687 Support new plugin content types for collections
  galaxy/constants.py
  galaxy/importer/finders.py
  galaxy/importer/loaders/plugin.py
  galaxy/main/migrations/0133_update_contenttype.py
Labels: area/backend
