Repository ansible/galaxy, pull requests merged in 2019-05, with the labels that each got.

#1775 Allow html pre tag to support code blocks
  galaxy/importer/utils/readme.py
Labels: area/backend, type/bug

#1804 Collection importer checks improvement
  galaxy/api/v2/tests/test_collection_views.py
  galaxy/api/v2/views/collection.py
  galaxy/worker/tasks/collection.py
Labels: area/backend

#1715 Move dependencies database check from importer to worker
  galaxy/importer/models.py
  galaxy/importer/tests/test_collection_info.py
  galaxy/worker/importers/collection.py
  galaxy/worker/tasks/collection.py
  galaxy/worker/tests/test_collection.py
Labels: area/backend

#1819 Fix order of assignment to match return values
  galaxy/worker/tasks/collection.py
Labels: area/backend

#1801 Make pip's timeout more forgiving while doing dev builds
  scripts/docker/dev/Dockerfile
Labels: area/infrastructure, status/new

#1824 Enforce unique names across collections, and repository roles
  galaxy/api/v2/views/collection.py
  galaxy/worker/tasks/repository.py
Labels: area/backend, priority/high

#1789 Rev Collection download_count on /artifact/ get
  galaxy/api/v2/tests/test_collection_version_views.py
  galaxy/api/v2/views/collection_version.py
Labels: area/backend, priority/high, status/in-progress, type/bug, type/enhancement

#1868 Optimize search performance
  galaxy/api/internal/search.py
Labels: area/backend
